### ISSUE TITLE
Using with Immutable.js

### ISSUE THREAD

**Issue by oskarer** [kolodny/redux-await#2]
I'm trying to use redux-await with Immutable.js, however it does not seem to work. The following was my code before trying Immutable.js, which works fine: 

``` javascript
import { createReducer } from 'redux-await';
const initialState = {
  user: null
}

const user = (state = initialState, action) => {
  switch (action.type) {
    case 'SIGN_IN':
      const { authToken } = action.payload.response;
      return Object.assign({}, state, {
        authToken
      })
    default:
      return state
  }
}

export default createReducer(user);
```

However trying the same thing with Immutable generates an error, saying that "undefined is not a function". Cannot figure out exactly where that is tho.

``` javascript
import { createReducer } from 'redux-await';
import { Map } from 'immutable';
const initialState = Map({})

let user = (state = initialState, action) => {
  switch (action.type) {
    case 'SIGN_IN':
      const { authToken } = action.payload.response;
      state.set('authToken', authToken);
      return state;
    default:
      return state
  }
}

export default createReducer(user);
```

Is redux-await suppose to work with Immutable.js or is it a limitation it has?

**Comment by kolodny** [comment]
hmm, well the way redux-await works is by changing the state, it assumes that it's a plain javascript object. This is probably why other modules like redux-form demand their own branch in the state tree. I think I'm gonna rewrite this to do that, expect this on V5

**Comment by kolodny** [comment]
Nice bug. The cause of this is that redux-await changes part of the state tree of the current reducer to keep track of the payload state. I think to solve this, I'll have an optional getting and setter passed into `createReducer` so you'd do something like this:

```js
import { createReducer } from 'redux-await';
import { Map } from 'immutable';
const initialState = Map({})

let user = (state = initialState, action) => {
  switch (action.type) {
    case 'SIGN_IN':
      const { authToken } = action.payload.response;
      state.set('authToken', authToken);
      return state;
    default:
      return state
  }
}

export default createReducer(user, {
  get: function(state) { return state.get('await') },
  set: function(state, data) { state.set('await', data) }
});
```

Would that make sense?

**Comment by kolodny** [comment]
redux-await is meant to be used with plain objects. In order to make it work with any other store type we would need to wrap the reducer state and either require the container to either use `connect` from `redux-await`, or get props from a custom function

Either 

``` diff
-- import { connect } from 'react-redux';
++ import { connect } from 'redux-await';
@connect(state => state)
class App extends Component {
}
```

or this:

``` diff
++ import { getProps } from 'redux-await';
render() {
--  const { dispatch, users } = this.props;
++  const { dispatch } = this.props;
++  const { users } = getProps(this.props)
}
```

**Comment by oskarer** [comment]
I was able to make a [very dirty fix](https://github.com/oskarer/redux-await/commit/26b073ec1cb750eead8c845f308751a39cf876c9) to get it to run with Immutable.js Maps, which obviously doesn't work with plain javascript objects. What do you think of this approach? Could redux-await be modified to handle both Immutable.js and plain javascript objects?

**Comment by kolodny** [comment]
If it works for your use case, then fork it and use that. My plan is to use a custom `connect`er similar to what `redux-form` does, something like this

``` js
export const function connect(mapStateToProps, ...rest) {
  return reduxConnect(state => {
    const props = mapStateToProps(state);
    const { statuses, errors } = state.await;
    return { ...props, statuses, errors };
  }, ...rest);
}
```

and also require control over a branch of the tree like most other higher order redux modules:

``` js
const reducers = combineReducers({
  todos: todosReducer,
  await: awaitReducer,
})
```

expect a v5 sometime soon

**Comment by kolodny** [comment]
BTW to use your fork, you would need to remove the `lib/` entry from your package.json, run `npm run build` then commit that then `npm install oskarer/redux-await` on your consumer project

**Comment by oskarer** [comment]
Alright, thanks! Closing this issue then.

**Comment by kolodny** [comment]
@oskarer Just pushed `5.0.0`, it should solve the issue you were having
